# Generated by Django 4.2.2 on 2023-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_discription_movie_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumpnail',
            field=models.ImageField(default='imageadding', upload_to='pics'),
            preserve_default=False,
        ),
    ]
