# Generated by Django 4.2.2 on 2023-07-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_thumpnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='thumpnail',
            new_name='img',
        ),
    ]
